### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DarcyCJ**
Fixed MIT course at Row83.
Row 82 info still to be verified.

### CODE REVIEW

**Comment by dukeofdisaster** [comment]
Reviewed; no objections

**Comment by vitalysim** [comment]
THANKS! Spread the repo so others can contribute

**Comment by scottareaume** [comment]
Have brother watching my every move steeling from sites on Telus data

**Comment by scottareaume** [comment]
I've been fighting this too long wasn't any of my doing won a prize been trying to steel

**Pull request merged**
