### PR TITLE
Added 3 new courses

### PR DESCRIPTION
**Pull request by deveyNull**

### CODE REVIEW

**Comment by dukeofdisaster** [comment]
@vitalysim I somewhat second this one as well; hoppersroppers.github.io now redirects to hoppersroppers.org, however I don't think the links in the description are necessary. Historically we haven't had links in descriptions, and hoppersroppers.org is easy to navigate, there is very clearly a "courses" tab that's self explanatory.

**Comment by deveyNull** [comment]
Removed links in description.

**Comment by dukeofdisaster** [comment]
@vitalysim per @deveyNull's changes i fully second this pull request.

**Comment by deveyNull** [comment]
Bumping the pull, thank you!

**Comment by vitalysim** [comment]
Thanks!!!

**Pull request merged**
