### PR TITLE
Reformatted subsections in Youtube Channels table

### PR DESCRIPTION
**Pull request by dukeofdisaster**
If there's something specific you suggest changing or formatting differently, please advise

-DoD

### CODE REVIEW

**Comment by vitalysim** [comment]
Can you please fetch the latest version of the repo and apply the reformatting to it?

**Comment by dukeofdisaster** [comment]
Yes, will try and complete today or tomorrow.

**Comment by dukeofdisaster** [comment]
Let me know what you think, if you want it cleaner I can just delete my fork and then clone and reformat the master again...but I just committed to my branch... tell me what you want to do! idk how to fetch, could read up on it more this evening.

**Comment by vitalysim** [comment]
If you can fork it again, I will appreciate it

**Pull request closed without merging**
