### PR TITLE
Added Xerosploit man in the middle framework

### PR DESCRIPTION
**Pull request by tiaghoalves**
I think [Xerosploit](https://github.com/LionSec/xerosploit) is a good tool to add, but not sure where put it :confused:

### CODE REVIEW

**Comment by vitalysim** [comment]
I think adding a new tool section will overwhelm the readme file.
How about creating a new file only for tools and creating a section for each category?

**Comment by tiaghoalves** [comment]
Alright, if you preferer sounds good for me.

**Comment by vitalysim** [comment]
Create a new tools.md file and start to add sections and links!

**Comment by vitalysim** [comment]
Thanks!!! looking forward to hear from you

**Comment by tiaghoalves** [comment]
Great thanks to you, I just keep collaborating to open source projects :smile:

**Pull request merged**
